# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.4.3'
  hooks:
    - id: ruff
      args: [ --fix, --exit-non-zero-on-fix ]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/psf/black
  rev: "24.4.2"
  hooks:
  - id: black

- repo: https://github.com/python-poetry/poetry
  rev: '1.8.0'
  hooks:
    - id: poetry-check
    - id: poetry-lock
    - id: poetry-export
      args: [ "--with", "docs", "--without-hashes", "-o", "docs/requirements.txt" ]

- repo: https://github.com/floatingpurr/sync_with_poetry
  rev: "1.1.0"
  hooks:
    - id: sync_with_poetry
