ci:
  skip:
    - poetry-lock
    - poetry-export
    - sync_with_poetry

repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 'v0.6.3'
  hooks:
    - id: ruff
      args: [ --fix, --exit-non-zero-on-fix ]
    - id: ruff-format

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files


- repo: https://github.com/python-poetry/poetry
  rev: '1.8.0'
  hooks:
    - id: poetry-lock
    - id: poetry-check
    - id: poetry-export
      args: [ "--with", "docs", "--without-hashes", "-o", "docs/requirements.txt" ]

- repo: https://github.com/floatingpurr/sync_with_poetry
  rev: "1.1.0"
  hooks:
    - id: sync_with_poetry
